const http = require('http');

// Test user registration with detailed server monitoring
const testData = JSON.stringify({
  username: 'comprehensive' + Date.now(),
  email: 'comprehensive' + Date.now() + '@example.com',
  password: 'SecurePass123!'
});

const options = {
  hostname: 'localhost',
  port: 4000,
  path: '/api/auth/register',
  method: 'POST',
  headers: {
    'Content-Type': 'application/json',
    'Content-Length': Buffer.byteLength(testData)
  }
};

console.log('🧪 Testing comprehensive user registration...');
console.log('📝 Test user data:', JSON.parse(testData));
console.log('🔗 Making request to:', `http://localhost:4000${options.path}`);
console.log('');

const req = http.request(options, (res) => {
  console.log(`📊 Status Code: ${res.statusCode}`);
  console.log(`📋 Response Headers:`, Object.keys(res.headers));

  let data = '';
  res.on('data', (chunk) => {
    data += chunk;
  });

  res.on('end', () => {
    console.log('\n📤 Response Body:');
    try {
      const response = JSON.parse(data);
      console.log(JSON.stringify(response, null, 2));

      if (res.statusCode === 201 && response.success) {
        console.log('\n✅ SUCCESS: Registration completed!');
        console.log(`🎉 User created: ${response.user.username}`);
        console.log(`🆔 User ID: ${response.user.id}`);

        // Check if starter pack was generated by testing character retrieval
        setTimeout(() => {
          testCharacterRetrieval(response.user.id);
        }, 1000);
      } else {
        console.log('\n❌ ERRORS DETECTED:');
        console.log(response);
      }
    } catch (e) {
      console.log('❌ JSON Parse error:', e.message);
      console.log('Raw response:', data);
    }
  });
});

req.on('error', (e) => {
  console.error('❌ Request error:', e.message);
});

req.write(testData);
req.end();

// Test character retrieval for the user
function testCharacterRetrieval(userId) {
  console.log('\n🎭 Testing character retrieval for user:', userId);

  const charOptions = {
    hostname: 'localhost',
    port: 4000,
    path: `/api/characters/user/${userId}`,
    method: 'GET',
    headers: {
      'Content-Type': 'application/json'
    }
  };

  const charReq = http.request(charOptions, (res) => {
    console.log(`📊 Character endpoint status: ${res.statusCode}`);

    let data = '';
    res.on('data', (chunk) => {
      data += chunk;
    });

    res.on('end', () => {
      try {
        const response = JSON.parse(data);
        console.log('🎭 User characters:', response.length || 0);
        if (response.length > 0) {
          console.log('✅ Starter pack characters generated successfully!');
          response.forEach((char, index) => {
            console.log(`  ${index + 1}. ${char.name} (${char.title})`);
          });
        } else {
          console.log('❌ No characters found - starter pack generation failed');
        }
      } catch (e) {
        console.log('❌ Character retrieval parse error:', e.message);
        console.log('Raw response:', data);
      }
    });
  });

  charReq.on('error', (e) => {
    console.error('❌ Character request error:', e.message);
  });

  charReq.end();
}
