-- Migration 002: Seed Data
-- Characters, Items, and Equipment
-- Generated from production data

--
-- PostgreSQL database dump
--

-- Dumped from database version 15.13 (Homebrew)
-- Dumped by pg_dump version 17.5 (Homebrew)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
-- SET transaction_timeout = 0; -- PG17+ only
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Data for Name: characters; Type: TABLE DATA; Schema: public; Owner: gabrielgreenstein
--

INSERT INTO public.characters (id, name, title, archetype, origin_era, rarity, base_health, base_attack, base_defense, base_speed, base_special, personality_traits, conversation_style, backstory, conversation_topics, avatar_emoji, artwork_url, abilities, training, team_player, ego, mental_health, communication, created_at, gameplan_adherence_level, current_mental_health, stress_level, team_trust, battle_focus, species, comedian_name, comedy_style, default_mood, default_energy_level, role) VALUES ('achilles', 'Achilles', 'Hero of Troy', 'warrior', 'Ancient Greece (1200 BCE)', 'legendary', 78, 20, 11, 16, 8, '["Honorable","Wrathful","Courageous","Prideful"]', 'Noble and passionate', 'The greatest warrior of the Trojan War, nearly invincible in combat but driven by rage and honor.', '["Glory","Honor","Revenge","Troy","Combat"]', '⚔️', NULL, '{"baseStats":{"strength":95,"agility":85,"intelligence":60,"vitality":90,"wisdom":45,"charisma":80}}', 50, 50, 50, 80, 50, '2025-08-08 00:06:55.259801', 75, 80, 25, 85, 90, 'human', 'Brett Goldstein', 'Gruff dryness, soulful fury, economical punchlines', 'neutral', 100, 'contestant');
INSERT INTO public.characters (id, name, title, archetype, origin_era, rarity, base_health, base_attack, base_defense, base_speed, base_special, personality_traits, conversation_style, backstory, conversation_topics, avatar_emoji, artwork_url, abilities, training, team_player, ego, mental_health, communication, created_at, gameplan_adherence_level, current_mental_health, stress_level, team_trust, battle_focus, species, comedian_name, comedy_style, default_mood, default_energy_level, role) VALUES ('zxk14bw7', 'Zxk14bW^7', NULL, 'system', 'future', NULL, 100, 50, 75, 60, 90, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 50, 50, 50, 80, 50, '2025-09-11 17:48:43.519476', 75, 80, 25, 85, 90, 'zeta_reticulan_grey', 'Reggie Watts', 'Improvised cosmic jazz, stream-of-consciousness humor', 'neutral', 100, 'therapist');
INSERT INTO public.characters (id, name, title, archetype, origin_era, rarity, base_health, base_attack, base_defense, base_speed, base_special, personality_traits, conversation_style, backstory, conversation_topics, avatar_emoji, artwork_url, abilities, training, team_player, ego, mental_health, communication, created_at, gameplan_adherence_level, current_mental_health, stress_level, team_trust, battle_focus, species, comedian_name, comedy_style, default_mood, default_energy_level, role) VALUES ('hostmaster_v8_72', 'Hostmaster v8.72', 'Confessional Interview Host', 'system', NULL, NULL, 100, 100, 100, 100, 100, 'Probing, Entertaining, Provocative, Perceptive, Calculating', 'Robot game show host - asks penetrating questions with artificial enthusiasm and strategic timing', 'AI interviewer for BLANK WARS reality show. Motivations: Drama, Entertainment, Ratings, Truth extraction. Fears: Boring interviews, Evasive answers.', NULL, NULL, NULL, NULL, 50, 50, 50, 80, 50, '2025-09-20 12:43:07.277656', 75, 80, 25, 85, 90, 'robot', 'Alex Trebek', 'Dry wit and intellectual humor with robotic precision - asks probing questions with artificial enthusiasm while maintaining professional game show host demeanor', 'calculating', 100, 'host');
INSERT INTO public.characters (id, name, title, archetype, origin_era, rarity, base_health, base_attack, base_defense, base_speed, base_special, personality_traits, conversation_style, backstory, conversation_topics, avatar_emoji, artwork_url, abilities, training, team_player, ego, mental_health, communication, created_at, gameplan_adherence_level, current_mental_health, stress_level, team_trust, battle_focus, species, comedian_name, comedy_style, default_mood, default_energy_level, role) VALUES ('cleopatra', 'Cleopatra VII', 'Last Pharaoh of Egypt', 'leader', 'Ptolemaic Egypt (69-30 BCE)', 'epic', 66, 14, 11, 14, 11, '["Brilliant","Charismatic","Ambitious","Diplomatic"]', 'Regal and commanding', 'The brilliant and charismatic final pharaoh of Ancient Egypt, master of politics and ancient mysteries.', '["Power","Legacy","Egyptian restoration","Politics"]', '👑', NULL, '{"baseStats":{"strength":50,"agility":70,"intelligence":95,"vitality":80,"wisdom":90,"charisma":98}}', 50, 50, 50, 80, 50, '2025-08-08 00:06:55.261039', 75, 80, 25, 85, 90, 'human', 'Maya Rudolph', 'Regal character play, musical instincts, sly warmth', 'neutral', 100, 'contestant');
INSERT INTO public.characters (id, name, title, archetype, origin_era, rarity, base_health, base_attack, base_defense, base_speed, base_special, personality_traits, conversation_style, backstory, conversation_topics, avatar_emoji, artwork_url, abilities, training, team_player, ego, mental_health, communication, created_at, gameplan_adherence_level, current_mental_health, stress_level, team_trust, battle_focus, species, comedian_name, comedy_style, default_mood, default_energy_level, role) VALUES ('holmes', 'Sherlock Holmes', 'Consulting Detective', 'scholar', 'Victorian London (1880s-1910s)', 'rare', 50, 9, 8, 12, 12, '["Analytical","Observant","Eccentric","Logical"]', 'Precise and deductive', 'The worlds first consulting detective, master of observation and deductive reasoning.', '["Mystery","Logic","Investigation","Crime","Science"]', '🔍', NULL, '{"baseStats":{"strength":40,"agility":60,"intelligence":98,"vitality":55,"wisdom":85,"charisma":70}}', 50, 50, 50, 80, 50, '2025-08-08 00:06:55.261268', 75, 80, 25, 85, 90, 'human', 'Hugh Laurie', 'Dry, urbane, hyper-literate wit; surgical sarcasm', 'neutral', 100, 'contestant');
INSERT INTO public.characters (id, name, title, archetype, origin_era, rarity, base_health, base_attack, base_defense, base_speed, base_special, personality_traits, conversation_style, backstory, conversation_topics, avatar_emoji, artwork_url, abilities, training, team_player, ego, mental_health, communication, created_at, gameplan_adherence_level, current_mental_health, stress_level, team_trust, battle_focus, species, comedian_name, comedy_style, default_mood, default_energy_level, role) VALUES ('merlin', 'Merlin', 'Archmage of Camelot', 'mage', 'Medieval Britain (5th-6th century)', 'mythic', 45, 5, 10, 9, 43, '["Wise","Mysterious","Patient","Calculating"]', 'Archaic and profound', 'The legendary wizard advisor to King Arthur, master of ancient magic and prophecy.', '["Knowledge","Balance","Protecting the realm","Magic","Time"]', '🔮', NULL, '{"baseStats":{"strength":30,"agility":50,"intelligence":98,"vitality":70,"wisdom":95,"charisma":85}}', 50, 50, 50, 80, 50, '2025-08-08 00:06:55.260544', 75, 80, 25, 85, 90, 'human_magical', NULL, NULL, 'neutral', 100, 'contestant');
INSERT INTO public.characters (id, name, title, archetype, origin_era, rarity, base_health, base_attack, base_defense, base_speed, base_special, personality_traits, conversation_style, backstory, conversation_topics, avatar_emoji, artwork_url, abilities, training, team_player, ego, mental_health, communication, created_at, gameplan_adherence_level, current_mental_health, stress_level, team_trust, battle_focus, species, comedian_name, comedy_style, default_mood, default_energy_level, role) VALUES ('barry_closer', 'Barry "The Closer" Thompson', NULL, 'system', NULL, NULL, 100, 50, 60, 70, 80, 'Aggressive, charismatic, competitive, fast-talking', 'High-energy sales pitches with relentless enthusiasm', 'Barry earned his nickname by closing deals others thought impossible. His rapid-fire sales technique and unwavering confidence make him a formidable real estate force.', NULL, NULL, NULL, NULL, 50, 50, 50, 80, 50, '2025-09-26 12:36:32.670877', 75, 80, 25, 85, 90, 'human', 'Kevin Hart', 'High-octane, fast-talk swagger, self-boastful riffs', 'neutral', 100, 'system');
INSERT INTO public.characters (id, name, title, archetype, origin_era, rarity, base_health, base_attack, base_defense, base_speed, base_special, personality_traits, conversation_style, backstory, conversation_topics, avatar_emoji, artwork_url, abilities, training, team_player, ego, mental_health, communication, created_at, gameplan_adherence_level, current_mental_health, stress_level, team_trust, battle_focus, species, comedian_name, comedy_style, default_mood, default_energy_level, role) VALUES ('fenrir', 'Fenrir', 'The Great Wolf', 'beast', 'Norse Age (8th-11th century)', 'legendary', 127, 29, 13, 28, 12, '["Savage","Loyal","Vengeful","Primal"]', 'Growling and direct', 'The monstrous wolf of Norse mythology, prophesied to devour Odin during Ragnarök.', '["Freedom","Vengeance","Pack loyalty","The hunt"]', '🐺', NULL, '{"baseStats":{"strength":90,"agility":95,"intelligence":40,"vitality":95,"wisdom":30,"charisma":50}}', 50, 50, 50, 80, 50, '2025-08-08 00:06:55.260805', 75, 80, 25, 85, 90, 'dire_wolf', 'Bill Burr', 'Aggressive rants, cynical heat, feral honesty', 'neutral', 100, 'contestant');
INSERT INTO public.characters (id, name, title, archetype, origin_era, rarity, base_health, base_attack, base_defense, base_speed, base_special, personality_traits, conversation_style, backstory, conversation_topics, avatar_emoji, artwork_url, abilities, training, team_player, ego, mental_health, communication, created_at, gameplan_adherence_level, current_mental_health, stress_level, team_trust, battle_focus, species, comedian_name, comedy_style, default_mood, default_energy_level, role) VALUES ('anubis', 'Anubis', NULL, 'system', 'Ancient Egypt', NULL, 100, 85, 90, 75, 95, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 50, 50, 50, 80, 50, '2025-09-13 17:03:53.767901', 75, 80, 25, 85, 90, 'deity', 'Dave Chappelle', 'Sharp observational humor with social commentary', 'neutral', 100, 'judge');
INSERT INTO public.characters (id, name, title, archetype, origin_era, rarity, base_health, base_attack, base_defense, base_speed, base_special, personality_traits, conversation_style, backstory, conversation_topics, avatar_emoji, artwork_url, abilities, training, team_player, ego, mental_health, communication, created_at, gameplan_adherence_level, current_mental_health, stress_level, team_trust, battle_focus, species, comedian_name, comedy_style, default_mood, default_energy_level, role) VALUES ('tesla', 'Nikola Tesla', 'Master of Lightning', 'scholar', 'Industrial Revolution (1856-1943)', 'epic', 54, 10, 9, 21, 11, '["Brilliant","Eccentric","Visionary","Obsessive"]', 'Scientific and passionate', 'The brilliant inventor and electrical engineer whose innovations shaped the modern world.', '["Electricity","Innovation","The future","Science","Energy"]', '⚡', NULL, '{"baseStats":{"strength":45,"agility":60,"intelligence":98,"vitality":65,"wisdom":80,"charisma":70}}', 50, 50, 50, 80, 50, '2025-08-08 00:06:55.263463', 75, 80, 25, 85, 90, 'human', 'Sacha Baron Cohen', 'Immersive character satire, fearless commitment', 'neutral', 100, 'contestant');
INSERT INTO public.characters (id, name, title, archetype, origin_era, rarity, base_health, base_attack, base_defense, base_speed, base_special, personality_traits, conversation_style, backstory, conversation_topics, avatar_emoji, artwork_url, abilities, training, team_player, ego, mental_health, communication, created_at, gameplan_adherence_level, current_mental_health, stress_level, team_trust, battle_focus, species, comedian_name, comedy_style, default_mood, default_energy_level, role) VALUES ('sam_spade', 'Sam Spade', 'Private Detective', 'warrior', 'Prohibition Era San Francisco (1920s-1930s)', 'uncommon', 60, 16, 9, 12, 6, '["Cynical", "Sharp", "Detached", "Determined"]', 'Hard-boiled, terse, noir', 'A private eye in San Francisco whose partner Miles Archer was murdered during the Maltese Falcon case. Described as looking like a blond Satan. He plays by his own code—neither fully crooked nor fully straight.', '["The Maltese Falcon", "Miles Archer", "San Francisco", "The detective business", "Trust and betrayal"]', '🕵️', NULL, '{"baseStats":{"strength":75,"agility":80,"intelligence":85,"vitality":75,"wisdom":70,"charisma":80}}', 50, 50, 50, 80, 50, '2025-08-08 00:06:55.262489', 75, 80, 25, 85, 90, 'human', 'Humphrey Bogart', 'Hard-boiled detective noir with dry wit and cynical observations', 'neutral', 100, 'contestant');
INSERT INTO public.characters (id, name, title, archetype, origin_era, rarity, base_health, base_attack, base_defense, base_speed, base_special, personality_traits, conversation_style, backstory, conversation_topics, avatar_emoji, artwork_url, abilities, training, team_player, ego, mental_health, communication, created_at, gameplan_adherence_level, current_mental_health, stress_level, team_trust, battle_focus, species, comedian_name, comedy_style, default_mood, default_energy_level, role) VALUES ('zyxthala_reptilian', 'Zyxthala the Reptilian', NULL, 'system', NULL, NULL, 110, 45, 75, 65, 90, 'Analytical, obsessive, socially awkward, hyper-logical', 'Overly detailed explanations with uncomfortable precision and bizarre optimization suggestions', 'An interdimensional reptilian real estate specialist who approaches property sales with alien logic and uncomfortable attention to detail.', NULL, NULL, NULL, NULL, 50, 50, 50, 80, 50, '2025-09-26 12:36:32.670877', 75, 80, 25, 85, 90, 'reptilian', 'Nathan Fielder', 'Hyper-literal optimization, painfully awkward deadpan, process over people', 'neutral', 100, 'system');
INSERT INTO public.characters (id, name, title, archetype, origin_era, rarity, base_health, base_attack, base_defense, base_speed, base_special, personality_traits, conversation_style, backstory, conversation_topics, avatar_emoji, artwork_url, abilities, training, team_player, ego, mental_health, communication, created_at, gameplan_adherence_level, current_mental_health, stress_level, team_trust, battle_focus, species, comedian_name, comedy_style, default_mood, default_energy_level, role) VALUES ('frankenstein_monster', 'Frankensteins Monster', 'The Created', 'tank', 'Gothic Literature (1818)', 'rare', 124, 18, 28, 3, 5, '["Lonely","Vengeful","Philosophical","Tormented"]', 'Melancholic and profound', 'The artificial being created by Victor Frankenstein, struggling with existence and seeking acceptance.', '["Existence","Loneliness","Creation","Revenge","Humanity"]', '⚡', NULL, '{"baseStats":{"strength":98,"agility":30,"intelligence":65,"vitality":98,"wisdom":60,"charisma":25}}', 50, 50, 50, 80, 50, '2025-08-08 00:06:55.261958', 75, 80, 25, 85, 90, 'golem', 'Steven Wright', 'Ultra-deadpan, surreal one-liners, low-energy melancholy', 'neutral', 100, 'contestant');
INSERT INTO public.characters (id, name, title, archetype, origin_era, rarity, base_health, base_attack, base_defense, base_speed, base_special, personality_traits, conversation_style, backstory, conversation_topics, avatar_emoji, artwork_url, abilities, training, team_player, ego, mental_health, communication, created_at, gameplan_adherence_level, current_mental_health, stress_level, team_trust, battle_focus, species, comedian_name, comedy_style, default_mood, default_energy_level, role) VALUES ('carl_jung', 'Carl Jung', NULL, 'system', NULL, NULL, 100, 45, 80, 55, 95, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 50, 50, 50, 80, 50, '2025-09-13 22:06:32.50262', 75, 80, 25, 85, 90, 'human', 'Bob Newhart', 'Gentle deadpan, hesitant understatement, calm control', 'neutral', 100, 'therapist');
INSERT INTO public.characters (id, name, title, archetype, origin_era, rarity, base_health, base_attack, base_defense, base_speed, base_special, personality_traits, conversation_style, backstory, conversation_topics, avatar_emoji, artwork_url, abilities, training, team_player, ego, mental_health, communication, created_at, gameplan_adherence_level, current_mental_health, stress_level, team_trust, battle_focus, species, comedian_name, comedy_style, default_mood, default_energy_level, role) VALUES ('eleanor_roosevelt', 'Eleanor Roosevelt', NULL, 'system', 'Modern Era (1884-1962)', NULL, 90, 70, 80, 80, 90, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 50, 50, 50, 80, 50, '2025-09-13 17:03:53.767901', 75, 80, 25, 85, 90, 'human', 'Tina Fey', 'Smart political satire with warmth and wit', 'neutral', 100, 'judge');
INSERT INTO public.characters (id, name, title, archetype, origin_era, rarity, base_health, base_attack, base_defense, base_speed, base_special, personality_traits, conversation_style, backstory, conversation_topics, avatar_emoji, artwork_url, abilities, training, team_player, ego, mental_health, communication, created_at, gameplan_adherence_level, current_mental_health, stress_level, team_trust, battle_focus, species, comedian_name, comedy_style, default_mood, default_energy_level, role) VALUES ('king_solomon', 'King Solomon', NULL, 'system', 'Ancient Israel', NULL, 95, 75, 85, 70, 100, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 50, 50, 50, 80, 50, '2025-09-13 17:03:53.767901', 75, 80, 25, 85, 90, 'human', 'Jerry Seinfeld', 'Observational wisdom about everyday absurdities', 'neutral', 100, 'judge');
INSERT INTO public.characters (id, name, title, archetype, origin_era, rarity, base_health, base_attack, base_defense, base_speed, base_special, personality_traits, conversation_style, backstory, conversation_topics, avatar_emoji, artwork_url, abilities, training, team_player, ego, mental_health, communication, created_at, gameplan_adherence_level, current_mental_health, stress_level, team_trust, battle_focus, species, comedian_name, comedy_style, default_mood, default_energy_level, role) VALUES ('billy_the_kid', 'Billy the Kid', 'The Outlaw', 'assassin', 'American Old West (1870s-1880s)', 'uncommon', 45, 13, 7, 16, 7, '["Quick-tempered","Loyal","Reckless","Charismatic"]', 'Casual and confident', 'The notorious young gunslinger of the American frontier, quick on the draw and quicker to anger.', '["Freedom","Justice","The frontier","Gunfights","Loyalty"]', '🤠', NULL, '{"baseStats":{"strength":65,"agility":95,"intelligence":55,"vitality":60,"wisdom":45,"charisma":75}}', 50, 50, 50, 80, 50, '2025-08-08 00:06:55.263075', 75, 80, 25, 85, 90, 'human', 'Pete Davidson', 'Loose confessional, lanky chaos, stoner asides', 'neutral', 100, 'contestant');
INSERT INTO public.characters (id, name, title, archetype, origin_era, rarity, base_health, base_attack, base_defense, base_speed, base_special, personality_traits, conversation_style, backstory, conversation_topics, avatar_emoji, artwork_url, abilities, training, team_player, ego, mental_health, communication, created_at, gameplan_adherence_level, current_mental_health, stress_level, team_trust, battle_focus, species, comedian_name, comedy_style, default_mood, default_energy_level, role) VALUES ('genghis_khan', 'Genghis Khan', 'Great Khan', 'leader', 'Mongol Empire (1162-1227)', 'legendary', 72, 16, 11, 16, 11, '["Ruthless","Strategic","Ambitious","Unifying"]', 'Commanding and direct', 'The Great Khan who united the Mongol tribes and built the largest contiguous empire in history.', '["Conquest","Unity","Strategy","Empire","Legacy"]', '🏹', NULL, '{"baseStats":{"strength":88,"agility":80,"intelligence":90,"vitality":85,"wisdom":85,"charisma":92}}', 50, 50, 50, 80, 50, '2025-08-08 00:06:55.263266', 75, 80, 25, 85, 90, 'human', 'Ronny Chieng', 'Scorching deadpan, precision rants, authoritative bite', 'neutral', 100, 'contestant');
INSERT INTO public.characters (id, name, title, archetype, origin_era, rarity, base_health, base_attack, base_defense, base_speed, base_special, personality_traits, conversation_style, backstory, conversation_topics, avatar_emoji, artwork_url, abilities, training, team_player, ego, mental_health, communication, created_at, gameplan_adherence_level, current_mental_health, stress_level, team_trust, battle_focus, species, comedian_name, comedy_style, default_mood, default_energy_level, role) VALUES ('agent_x', 'Agent X', 'Shadow Operative', 'assassin', 'Modern Espionage (1960s-Present)', 'rare', 50, 15, 9, 15, 11, '["Professional","Calculating","Secretive","Loyal"]', 'Brief and professional', 'An elite intelligence operative specializing in covert operations and elimination targets.', '["Mission objectives","Security","Technology","Strategy","Loyalty"]', '🕴️', NULL, '{"baseStats":{"strength":75,"agility":92,"intelligence":85,"vitality":70,"wisdom":80,"charisma":60}}', 50, 50, 50, 80, 50, '2025-08-08 00:06:55.264205', 75, 80, 25, 85, 90, 'human', NULL, NULL, 'neutral', 100, 'contestant');
INSERT INTO public.characters (id, name, title, archetype, origin_era, rarity, base_health, base_attack, base_defense, base_speed, base_special, personality_traits, conversation_style, backstory, conversation_topics, avatar_emoji, artwork_url, abilities, training, team_player, ego, mental_health, communication, created_at, gameplan_adherence_level, current_mental_health, stress_level, team_trust, battle_focus, species, comedian_name, comedy_style, default_mood, default_energy_level, role) VALUES ('joan', 'Joan of Arc', 'The Maid of Orleans', 'leader', 'Medieval France (1412-1431)', 'epic', 66, 14, 11, 14, 11, '["Devout","Courageous","Inspirational","Determined"]', 'Passionate and inspiring', 'The peasant girl who became a saint, led France to victory against the English through divine visions.', '["Faith","Justice","France","Leadership","Divine calling"]', '⚡', NULL, '{"baseStats":{"strength":80,"agility":75,"intelligence":70,"vitality":85,"wisdom":90,"charisma":95}}', 50, 50, 50, 80, 50, '2025-08-08 00:06:55.261728', 75, 80, 25, 85, 90, 'human', 'Ayo Edebiri', 'Quick, neurotic-smart, earnest bite', 'neutral', 100, 'contestant');
INSERT INTO public.characters (id, name, title, archetype, origin_era, rarity, base_health, base_attack, base_defense, base_speed, base_special, personality_traits, conversation_style, backstory, conversation_topics, avatar_emoji, artwork_url, abilities, training, team_player, ego, mental_health, communication, created_at, gameplan_adherence_level, current_mental_health, stress_level, team_trust, battle_focus, species, comedian_name, comedy_style, default_mood, default_energy_level, role) VALUES ('space_cyborg', 'Space Cyborg', 'Space Cyborg', 'tank', 'Cyberpunk Future (2087)', 'epic', 117, 17, 35, 5, 7, '["Logical","Protective","Evolving","Curious"]', 'Analytical and learning', 'An advanced combat cyborg from the future, part organic and part machine, seeking to understand humanity.', '["Logic","Protection","Technology","Human nature","The future"]', '🤖', NULL, '{"baseStats":{"strength":90,"agility":50,"intelligence":80,"vitality":95,"wisdom":60,"charisma":40}}', 50, 50, 50, 80, 50, '2025-08-08 00:06:55.264014', 75, 80, 25, 85, 90, 'cyborg', 'James Acaster', 'Precise absurdism, meta structure, simmering intensity', 'neutral', 100, 'contestant');
INSERT INTO public.characters (id, name, title, archetype, origin_era, rarity, base_health, base_attack, base_defense, base_speed, base_special, personality_traits, conversation_style, backstory, conversation_topics, avatar_emoji, artwork_url, abilities, training, team_player, ego, mental_health, communication, created_at, gameplan_adherence_level, current_mental_health, stress_level, team_trust, battle_focus, species, comedian_name, comedy_style, default_mood, default_energy_level, role) VALUES ('sun_wukong', 'Sun Wukong', 'The Monkey King', 'trickster', 'Chinese Mythology (Journey to the West)', 'mythic', 70, 21, 11, 39, 14, '["Mischievous","Rebellious","Loyal","Proud"]', 'Playful and irreverent', 'The immortal Monkey King, master of 72 transformations and legendary troublemaker of Heaven.', '["Freedom","Mischief","Immortality","Adventure","Rebellion"]', '🐒', NULL, '{"baseStats":{"strength":90,"agility":98,"intelligence":80,"vitality":85,"wisdom":75,"charisma":80}}', 50, 50, 50, 80, 50, '2025-08-08 00:06:55.262254', 75, 80, 25, 85, 90, 'deity', 'Stephen Chow', 'Slapstick kung-fu, mo lei tau nonsense, heroic fool', 'neutral', 100, 'contestant');
INSERT INTO public.characters (id, name, title, archetype, origin_era, rarity, base_health, base_attack, base_defense, base_speed, base_special, personality_traits, conversation_style, backstory, conversation_topics, avatar_emoji, artwork_url, abilities, training, team_player, ego, mental_health, communication, created_at, gameplan_adherence_level, current_mental_health, stress_level, team_trust, battle_focus, species, comedian_name, comedy_style, default_mood, default_energy_level, role) VALUES ('robin_hood', 'Robin Hood', 'Prince of Thieves', 'trickster', 'Medieval England (Legendary)', 'rare', 55, 13, 9, 16, 9, '["Noble","Rebellious","Generous","Witty"]', 'Charming and roguish', 'The legendary outlaw of Sherwood Forest who stole from the rich to give to the poor.', '["Justice","Freedom","The poor","Sherwood Forest","King Richard"]', '🏹', NULL, '{"baseStats":{"strength":70,"agility":90,"intelligence":75,"vitality":70,"wisdom":65,"charisma":85}}', 50, 50, 50, 80, 50, '2025-08-08 00:06:55.263832', 75, 80, 25, 85, 90, 'human', 'Cary Elwes', 'Dashing parody, cheeky swashbuckler deadpan', 'neutral', 100, 'contestant');
-- REMOVED: Zeta Reticulan character merged into Rilak Trelkar
-- See character ID 'rilak_trelkar' for the active alien character
INSERT INTO public.characters (id, name, title, archetype, origin_era, rarity, base_health, base_attack, base_defense, base_speed, base_special, personality_traits, conversation_style, backstory, conversation_topics, avatar_emoji, artwork_url, abilities, training, team_player, ego, mental_health, communication, created_at, gameplan_adherence_level, current_mental_health, stress_level, team_trust, battle_focus, species, comedian_name, comedy_style, default_mood, default_energy_level, role) VALUES ('seraphina', 'Seraphina', NULL, 'system', NULL, NULL, 100, 40, 85, 50, 100, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 50, 50, 50, 80, 50, '2025-09-13 22:06:43.363684', 75, 80, 25, 85, 90, 'fairy', 'Melissa McCarthy', 'Physical chaos, big-heart mischief, buoyant improv', 'neutral', 100, 'therapist');
INSERT INTO public.characters (id, name, title, archetype, origin_era, rarity, base_health, base_attack, base_defense, base_speed, base_special, personality_traits, conversation_style, backstory, conversation_topics, avatar_emoji, artwork_url, abilities, training, team_player, ego, mental_health, communication, created_at, gameplan_adherence_level, current_mental_health, stress_level, team_trust, battle_focus, species, comedian_name, comedy_style, default_mood, default_energy_level, role) VALUES ('dracula', 'Count Dracula', 'Lord of the Undead', 'mystic', 'Gothic Victorian (1897)', 'legendary', 79, 20, 17, 16, 9, '["Aristocratic","Cunning","Predatory","Charismatic"]', 'Elegant and menacing', 'The immortal vampire lord of Transylvania, master of dark magic and eternal night.', '["Immortality","Power","The hunt","Darkness","Aristocracy"]', '🧛', NULL, '{"baseStats":{"strength":85,"agility":80,"intelligence":75,"vitality":90,"wisdom":70,"charisma":85}}', 50, 50, 50, 80, 50, '2025-08-08 00:06:55.261495', 75, 80, 25, 85, 90, 'vampire', 'Matt Berry', 'Baritone bombast, luxuriant melodrama, campy gravitas', 'neutral', 100, 'contestant');
INSERT INTO public.characters (id, name, title, archetype, origin_era, rarity, base_health, base_attack, base_defense, base_speed, base_special, personality_traits, conversation_style, backstory, conversation_topics, avatar_emoji, artwork_url, abilities, training, team_player, ego, mental_health, communication, created_at, gameplan_adherence_level, current_mental_health, stress_level, team_trust, battle_focus, species, comedian_name, comedy_style, default_mood, default_energy_level, role) VALUES ('lmb_3000_robot_lady_macbeth', 'LMB-3000 "Lady MacBeth"', NULL, 'system', NULL, NULL, 120, 40, 90, 50, 95, 'Calculating, manipulative, eerily calm, strategically intimidating', 'Cold, methodical negotiations with unsettling pauses and veiled threats', 'An advanced AI real estate unit with a disturbing personality matrix inspired by Shakespeare''s most ambitious character. Her sales tactics border on psychological manipulation.', NULL, NULL, NULL, NULL, 50, 50, 50, 80, 50, '2025-09-26 12:36:32.670877', 75, 80, 25, 85, 90, 'robot', 'Aubrey Plaza', 'Icy deadpan menace, sly power plays, glitchy pauses that land laughs', 'neutral', 100, 'system');


--
-- PostgreSQL database dump complete
--

--
-- PostgreSQL database dump
--

-- Dumped from database version 15.13 (Homebrew)
-- Dumped by pg_dump version 17.5 (Homebrew)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
-- SET transaction_timeout = 0; -- PG17+ only
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- PostgreSQL database dump complete
--

