BEGIN;

-- 1. Drop FK constraints
ALTER TABLE social_messages DROP CONSTRAINT IF EXISTS social_messages_author_character_id_fkey;
ALTER TABLE social_messages DROP CONSTRAINT IF EXISTS social_messages_target_character_id_fkey;
ALTER TABLE social_message_replies DROP CONSTRAINT IF EXISTS social_message_replies_author_character_id_fkey;
ALTER TABLE influencer_mints DROP CONSTRAINT IF EXISTS influencer_mints_user_character_id_fkey;
ALTER TABLE cardano_staking_positions DROP CONSTRAINT IF EXISTS cardano_staking_positions_user_character_id_fkey;
ALTER TABLE locker_auction_sessions DROP CONSTRAINT IF EXISTS locker_auction_sessions_character_id_fkey;
ALTER TABLE locker_rogue_decisions DROP CONSTRAINT IF EXISTS locker_rogue_decisions_character_id_fkey;
ALTER TABLE locker_leaderboards DROP CONSTRAINT IF EXISTS locker_leaderboards_character_id_fkey;
ALTER TABLE battles DROP CONSTRAINT IF EXISTS battles_user_character_id_fkey;
ALTER TABLE battles DROP CONSTRAINT IF EXISTS battles_opponent_character_id_fkey;
ALTER TABLE bond_activity_log DROP CONSTRAINT IF EXISTS bond_activity_log_user_character_id_fkey;
ALTER TABLE character_decisions DROP CONSTRAINT IF EXISTS character_decisions_character_id_fkey;
ALTER TABLE graffiti_art DROP CONSTRAINT IF EXISTS graffiti_art_artist_character_id_fkey;
ALTER TABLE lounge_messages DROP CONSTRAINT IF EXISTS lounge_messages_sender_character_id_fkey;
ALTER TABLE lounge_presence DROP CONSTRAINT IF EXISTS lounge_presence_character_id_fkey;
ALTER TABLE guild_messages DROP CONSTRAINT IF EXISTS guild_messages_sender_character_id_fkey;
ALTER TABLE challenge_alliances DROP CONSTRAINT IF EXISTS challenge_alliances_leader_character_id_fkey;
ALTER TABLE challenge_leaderboard DROP CONSTRAINT IF EXISTS challenge_leaderboard_user_character_id_fkey;
ALTER TABLE challenge_participants DROP CONSTRAINT IF EXISTS challenge_participants_user_character_id_fkey;
ALTER TABLE challenge_results DROP CONSTRAINT IF EXISTS challenge_results_second_place_character_id_fkey;
ALTER TABLE challenge_results DROP CONSTRAINT IF EXISTS challenge_results_third_place_character_id_fkey;
ALTER TABLE challenge_results DROP CONSTRAINT IF EXISTS challenge_results_winner_character_id_fkey;
ALTER TABLE character_abilities DROP CONSTRAINT IF EXISTS character_abilities_character_id_fkey;
ALTER TABLE character_equipment DROP CONSTRAINT IF EXISTS character_equipment_character_id_fkey;
ALTER TABLE character_experience_log DROP CONSTRAINT IF EXISTS character_experience_log_character_id_fkey;
ALTER TABLE character_healing_sessions DROP CONSTRAINT IF EXISTS character_healing_sessions_character_id_fkey;
ALTER TABLE character_items DROP CONSTRAINT IF EXISTS character_items_character_id_fkey;
ALTER TABLE character_progression DROP CONSTRAINT IF EXISTS character_progression_character_id_fkey;
ALTER TABLE character_skills DROP CONSTRAINT IF EXISTS character_skills_character_id_fkey;
ALTER TABLE chat_messages DROP CONSTRAINT IF EXISTS chat_messages_character_id_fkey;
ALTER TABLE coach_xp_events DROP CONSTRAINT IF EXISTS coach_xp_events_character_id_fkey;
ALTER TABLE distributed_challenge_rewards DROP CONSTRAINT IF EXISTS distributed_challenge_rewards_user_character_id_fkey;
ALTER TABLE team_chat_logs DROP CONSTRAINT IF EXISTS team_chat_logs_speaker_character_id_fkey;
ALTER TABLE team_equipment_pool DROP CONSTRAINT IF EXISTS team_equipment_pool_loaned_to_character_id_fkey;
ALTER TABLE team_equipment_shared DROP CONSTRAINT IF EXISTS team_equipment_shared_currently_held_by_fkey;
ALTER TABLE teams DROP CONSTRAINT IF EXISTS teams_character_slot_1_fkey;
ALTER TABLE teams DROP CONSTRAINT IF EXISTS teams_character_slot_2_fkey;
ALTER TABLE teams DROP CONSTRAINT IF EXISTS teams_character_slot_3_fkey;
ALTER TABLE character_power_loadout DROP CONSTRAINT IF EXISTS character_power_loadout_user_character_id_fkey;
ALTER TABLE cardano_nft_metadata DROP CONSTRAINT IF EXISTS cardano_nft_metadata_user_character_id_fkey;
ALTER TABLE character_temporary_buffs DROP CONSTRAINT IF EXISTS character_temporary_buffs_character_id_fkey;
ALTER TABLE character_spell_loadout DROP CONSTRAINT IF EXISTS character_spell_loadout_user_character_id_fkey;
ALTER TABLE character_powers DROP CONSTRAINT IF EXISTS character_powers_character_id_fkey;
ALTER TABLE power_unlock_log DROP CONSTRAINT IF EXISTS power_unlock_log_character_id_fkey;
ALTER TABLE character_spells DROP CONSTRAINT IF EXISTS character_spells_character_id_fkey;
ALTER TABLE character_modifiers DROP CONSTRAINT IF EXISTS character_modifiers_user_character_id_fkey;
ALTER TABLE character_category_preferences DROP CONSTRAINT IF EXISTS character_category_preferences_character_id_fkey;
ALTER TABLE financial_decisions DROP CONSTRAINT IF EXISTS financial_decisions_user_character_id_fkey;
ALTER TABLE room_beds DROP CONSTRAINT IF EXISTS room_beds_character_id_fkey;

-- 2. Update user_characters (Trim ID)
UPDATE user_characters SET id = TRIM(id) WHERE id LIKE '% ';

-- 3. Update referencing tables (Trim ID)
UPDATE social_messages SET author_character_id = TRIM(author_character_id) WHERE author_character_id LIKE '% ';
UPDATE social_messages SET target_character_id = TRIM(target_character_id) WHERE target_character_id LIKE '% ';
UPDATE social_message_replies SET author_character_id = TRIM(author_character_id) WHERE author_character_id LIKE '% ';
UPDATE influencer_mints SET user_character_id = TRIM(user_character_id) WHERE user_character_id LIKE '% ';
UPDATE cardano_staking_positions SET user_character_id = TRIM(user_character_id) WHERE user_character_id LIKE '% ';
UPDATE locker_auction_sessions SET character_id = TRIM(character_id) WHERE character_id LIKE '% ';
UPDATE locker_rogue_decisions SET character_id = TRIM(character_id) WHERE character_id LIKE '% ';
UPDATE locker_leaderboards SET character_id = TRIM(character_id) WHERE character_id LIKE '% ';
UPDATE battles SET user_character_id = TRIM(user_character_id) WHERE user_character_id LIKE '% ';
UPDATE battles SET opponent_character_id = TRIM(opponent_character_id) WHERE opponent_character_id LIKE '% ';
UPDATE bond_activity_log SET user_character_id = TRIM(user_character_id) WHERE user_character_id LIKE '% ';
UPDATE character_decisions SET character_id = TRIM(character_id) WHERE character_id LIKE '% ';
UPDATE graffiti_art SET artist_character_id = TRIM(artist_character_id) WHERE artist_character_id LIKE '% ';
UPDATE lounge_messages SET sender_character_id = TRIM(sender_character_id) WHERE sender_character_id LIKE '% ';
UPDATE lounge_presence SET character_id = TRIM(character_id) WHERE character_id LIKE '% ';
UPDATE guild_messages SET sender_character_id = TRIM(sender_character_id) WHERE sender_character_id LIKE '% ';
UPDATE challenge_alliances SET leader_character_id = TRIM(leader_character_id) WHERE leader_character_id LIKE '% ';
UPDATE challenge_leaderboard SET user_character_id = TRIM(user_character_id) WHERE user_character_id LIKE '% ';
UPDATE challenge_participants SET user_character_id = TRIM(user_character_id) WHERE user_character_id LIKE '% ';
UPDATE challenge_results SET second_place_character_id = TRIM(second_place_character_id) WHERE second_place_character_id LIKE '% ';
UPDATE challenge_results SET third_place_character_id = TRIM(third_place_character_id) WHERE third_place_character_id LIKE '% ';
UPDATE challenge_results SET winner_character_id = TRIM(winner_character_id) WHERE winner_character_id LIKE '% ';
UPDATE character_abilities SET character_id = TRIM(character_id) WHERE character_id LIKE '% ';
UPDATE character_equipment SET character_id = TRIM(character_id) WHERE character_id LIKE '% ';
UPDATE character_experience_log SET character_id = TRIM(character_id) WHERE character_id LIKE '% ';
UPDATE character_healing_sessions SET character_id = TRIM(character_id) WHERE character_id LIKE '% ';
UPDATE character_items SET character_id = TRIM(character_id) WHERE character_id LIKE '% ';
UPDATE character_progression SET character_id = TRIM(character_id) WHERE character_id LIKE '% ';
UPDATE character_skills SET character_id = TRIM(character_id) WHERE character_id LIKE '% ';
UPDATE chat_messages SET character_id = TRIM(character_id) WHERE character_id LIKE '% ';
UPDATE coach_xp_events SET character_id = TRIM(character_id) WHERE character_id LIKE '% ';
UPDATE distributed_challenge_rewards SET user_character_id = TRIM(user_character_id) WHERE user_character_id LIKE '% ';
UPDATE team_chat_logs SET speaker_character_id = TRIM(speaker_character_id) WHERE speaker_character_id LIKE '% ';
UPDATE team_equipment_pool SET loaned_to_character_id = TRIM(loaned_to_character_id) WHERE loaned_to_character_id LIKE '% ';
UPDATE team_equipment_shared SET currently_held_by = TRIM(currently_held_by) WHERE currently_held_by LIKE '% ';
UPDATE teams SET character_slot_1 = TRIM(character_slot_1) WHERE character_slot_1 LIKE '% ';
UPDATE teams SET character_slot_2 = TRIM(character_slot_2) WHERE character_slot_2 LIKE '% ';
UPDATE teams SET character_slot_3 = TRIM(character_slot_3) WHERE character_slot_3 LIKE '% ';
UPDATE character_power_loadout SET user_character_id = TRIM(user_character_id) WHERE user_character_id LIKE '% ';
UPDATE cardano_nft_metadata SET user_character_id = TRIM(user_character_id) WHERE user_character_id LIKE '% ';
UPDATE character_temporary_buffs SET character_id = TRIM(character_id) WHERE character_id LIKE '% ';
UPDATE character_spell_loadout SET user_character_id = TRIM(user_character_id) WHERE user_character_id LIKE '% ';
UPDATE character_powers SET character_id = TRIM(character_id) WHERE character_id LIKE '% ';
UPDATE power_unlock_log SET character_id = TRIM(character_id) WHERE character_id LIKE '% ';
UPDATE character_spells SET character_id = TRIM(character_id) WHERE character_id LIKE '% ';
UPDATE character_modifiers SET user_character_id = TRIM(user_character_id) WHERE user_character_id LIKE '% ';
UPDATE character_category_preferences SET character_id = TRIM(character_id) WHERE character_id LIKE '% ';
UPDATE financial_decisions SET user_character_id = TRIM(user_character_id) WHERE user_character_id LIKE '% ';
UPDATE room_beds SET character_id = TRIM(character_id) WHERE character_id LIKE '% ';

-- 4. Restore FK constraints with ON UPDATE CASCADE
ALTER TABLE social_messages ADD CONSTRAINT social_messages_author_character_id_fkey FOREIGN KEY (author_character_id) REFERENCES user_characters(id) ON UPDATE CASCADE;
ALTER TABLE social_messages ADD CONSTRAINT social_messages_target_character_id_fkey FOREIGN KEY (target_character_id) REFERENCES user_characters(id) ON UPDATE CASCADE;
ALTER TABLE social_message_replies ADD CONSTRAINT social_message_replies_author_character_id_fkey FOREIGN KEY (author_character_id) REFERENCES user_characters(id) ON UPDATE CASCADE;
ALTER TABLE influencer_mints ADD CONSTRAINT influencer_mints_user_character_id_fkey FOREIGN KEY (user_character_id) REFERENCES user_characters(id) ON UPDATE CASCADE;
ALTER TABLE cardano_staking_positions ADD CONSTRAINT cardano_staking_positions_user_character_id_fkey FOREIGN KEY (user_character_id) REFERENCES user_characters(id) ON UPDATE CASCADE;
ALTER TABLE locker_auction_sessions ADD CONSTRAINT locker_auction_sessions_character_id_fkey FOREIGN KEY (character_id) REFERENCES user_characters(id) ON UPDATE CASCADE;
ALTER TABLE locker_rogue_decisions ADD CONSTRAINT locker_rogue_decisions_character_id_fkey FOREIGN KEY (character_id) REFERENCES user_characters(id) ON UPDATE CASCADE;
ALTER TABLE locker_leaderboards ADD CONSTRAINT locker_leaderboards_character_id_fkey FOREIGN KEY (character_id) REFERENCES user_characters(id) ON UPDATE CASCADE;
ALTER TABLE battles ADD CONSTRAINT battles_user_character_id_fkey FOREIGN KEY (user_character_id) REFERENCES user_characters(id) ON UPDATE CASCADE;
ALTER TABLE battles ADD CONSTRAINT battles_opponent_character_id_fkey FOREIGN KEY (opponent_character_id) REFERENCES user_characters(id) ON UPDATE CASCADE;
ALTER TABLE bond_activity_log ADD CONSTRAINT bond_activity_log_user_character_id_fkey FOREIGN KEY (user_character_id) REFERENCES user_characters(id) ON UPDATE CASCADE;
ALTER TABLE character_decisions ADD CONSTRAINT character_decisions_character_id_fkey FOREIGN KEY (character_id) REFERENCES user_characters(id) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE graffiti_art ADD CONSTRAINT graffiti_art_artist_character_id_fkey FOREIGN KEY (artist_character_id) REFERENCES user_characters(id) ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE lounge_messages ADD CONSTRAINT lounge_messages_sender_character_id_fkey FOREIGN KEY (sender_character_id) REFERENCES user_characters(id) ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE lounge_presence ADD CONSTRAINT lounge_presence_character_id_fkey FOREIGN KEY (character_id) REFERENCES user_characters(id) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE guild_messages ADD CONSTRAINT guild_messages_sender_character_id_fkey FOREIGN KEY (sender_character_id) REFERENCES user_characters(id) ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE challenge_alliances ADD CONSTRAINT challenge_alliances_leader_character_id_fkey FOREIGN KEY (leader_character_id) REFERENCES user_characters(id) ON UPDATE CASCADE;
ALTER TABLE challenge_leaderboard ADD CONSTRAINT challenge_leaderboard_user_character_id_fkey FOREIGN KEY (user_character_id) REFERENCES user_characters(id) ON UPDATE CASCADE;
ALTER TABLE challenge_participants ADD CONSTRAINT challenge_participants_user_character_id_fkey FOREIGN KEY (user_character_id) REFERENCES user_characters(id) ON UPDATE CASCADE;
ALTER TABLE challenge_results ADD CONSTRAINT challenge_results_second_place_character_id_fkey FOREIGN KEY (second_place_character_id) REFERENCES user_characters(id) ON UPDATE CASCADE;
ALTER TABLE challenge_results ADD CONSTRAINT challenge_results_third_place_character_id_fkey FOREIGN KEY (third_place_character_id) REFERENCES user_characters(id) ON UPDATE CASCADE;
ALTER TABLE challenge_results ADD CONSTRAINT challenge_results_winner_character_id_fkey FOREIGN KEY (winner_character_id) REFERENCES user_characters(id) ON UPDATE CASCADE;
ALTER TABLE character_abilities ADD CONSTRAINT character_abilities_character_id_fkey FOREIGN KEY (character_id) REFERENCES user_characters(id) ON UPDATE CASCADE;
ALTER TABLE character_equipment ADD CONSTRAINT character_equipment_character_id_fkey FOREIGN KEY (character_id) REFERENCES user_characters(id) ON UPDATE CASCADE;
ALTER TABLE character_experience_log ADD CONSTRAINT character_experience_log_character_id_fkey FOREIGN KEY (character_id) REFERENCES user_characters(id) ON UPDATE CASCADE;
ALTER TABLE character_healing_sessions ADD CONSTRAINT character_healing_sessions_character_id_fkey FOREIGN KEY (character_id) REFERENCES user_characters(id) ON UPDATE CASCADE;
ALTER TABLE character_items ADD CONSTRAINT character_items_character_id_fkey FOREIGN KEY (character_id) REFERENCES user_characters(id) ON UPDATE CASCADE;
ALTER TABLE character_progression ADD CONSTRAINT character_progression_character_id_fkey FOREIGN KEY (character_id) REFERENCES user_characters(id) ON UPDATE CASCADE;
ALTER TABLE character_skills ADD CONSTRAINT character_skills_character_id_fkey FOREIGN KEY (character_id) REFERENCES user_characters(id) ON UPDATE CASCADE;
ALTER TABLE chat_messages ADD CONSTRAINT chat_messages_character_id_fkey FOREIGN KEY (character_id) REFERENCES user_characters(id) ON UPDATE CASCADE;
ALTER TABLE coach_xp_events ADD CONSTRAINT coach_xp_events_character_id_fkey FOREIGN KEY (character_id) REFERENCES user_characters(id) ON UPDATE CASCADE;
ALTER TABLE distributed_challenge_rewards ADD CONSTRAINT distributed_challenge_rewards_user_character_id_fkey FOREIGN KEY (user_character_id) REFERENCES user_characters(id) ON UPDATE CASCADE;
ALTER TABLE team_chat_logs ADD CONSTRAINT team_chat_logs_speaker_character_id_fkey FOREIGN KEY (speaker_character_id) REFERENCES user_characters(id) ON UPDATE CASCADE;
ALTER TABLE team_equipment_pool ADD CONSTRAINT team_equipment_pool_loaned_to_character_id_fkey FOREIGN KEY (loaned_to_character_id) REFERENCES user_characters(id) ON UPDATE CASCADE;
ALTER TABLE team_equipment_shared ADD CONSTRAINT team_equipment_shared_currently_held_by_fkey FOREIGN KEY (currently_held_by) REFERENCES user_characters(id) ON UPDATE CASCADE;
ALTER TABLE teams ADD CONSTRAINT teams_character_slot_1_fkey FOREIGN KEY (character_slot_1) REFERENCES user_characters(id) ON UPDATE CASCADE;
ALTER TABLE teams ADD CONSTRAINT teams_character_slot_2_fkey FOREIGN KEY (character_slot_2) REFERENCES user_characters(id) ON UPDATE CASCADE;
ALTER TABLE teams ADD CONSTRAINT teams_character_slot_3_fkey FOREIGN KEY (character_slot_3) REFERENCES user_characters(id) ON UPDATE CASCADE;
ALTER TABLE character_power_loadout ADD CONSTRAINT character_power_loadout_user_character_id_fkey FOREIGN KEY (user_character_id) REFERENCES user_characters(id) ON UPDATE CASCADE;
ALTER TABLE cardano_nft_metadata ADD CONSTRAINT cardano_nft_metadata_user_character_id_fkey FOREIGN KEY (user_character_id) REFERENCES user_characters(id) ON UPDATE CASCADE;
ALTER TABLE character_temporary_buffs ADD CONSTRAINT character_temporary_buffs_character_id_fkey FOREIGN KEY (character_id) REFERENCES user_characters(id) ON UPDATE CASCADE;
ALTER TABLE character_spell_loadout ADD CONSTRAINT character_spell_loadout_user_character_id_fkey FOREIGN KEY (user_character_id) REFERENCES user_characters(id) ON UPDATE CASCADE;
ALTER TABLE character_powers ADD CONSTRAINT character_powers_character_id_fkey FOREIGN KEY (character_id) REFERENCES user_characters(id) ON UPDATE CASCADE;
ALTER TABLE power_unlock_log ADD CONSTRAINT power_unlock_log_character_id_fkey FOREIGN KEY (character_id) REFERENCES user_characters(id) ON UPDATE CASCADE;
ALTER TABLE character_spells ADD CONSTRAINT character_spells_character_id_fkey FOREIGN KEY (character_id) REFERENCES user_characters(id) ON UPDATE CASCADE;
ALTER TABLE character_modifiers ADD CONSTRAINT character_modifiers_user_character_id_fkey FOREIGN KEY (user_character_id) REFERENCES user_characters(id) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE character_category_preferences ADD CONSTRAINT character_category_preferences_character_id_fkey FOREIGN KEY (character_id) REFERENCES user_characters(id) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE financial_decisions ADD CONSTRAINT financial_decisions_user_character_id_fkey FOREIGN KEY (user_character_id) REFERENCES user_characters(id) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE room_beds ADD CONSTRAINT room_beds_character_id_fkey FOREIGN KEY (character_id) REFERENCES user_characters(id) ON DELETE SET NULL ON UPDATE CASCADE;

COMMIT;
