// AUTO-GENERATED FILE - DO NOT EDIT
// Generated by shared/types/scripts/generate-from-db.ts
// Run `npm run generate` from shared/types/ to regenerate

// This file is generated from the database schema
// If the database is unavailable, the build will fail (no fallbacks)
// These types are shared between frontend and backend

export type Archetype = 'assassin' | 'beast' | 'beastmaster' | 'detective' | 'leader' | 'mage' | 'magical_appliance' | 'mystic' | 'scholar' | 'system' | 'tank' | 'trickster' | 'warrior';

export type Species = 'angel' | 'cyborg' | 'deity' | 'dinosaur' | 'dire_wolf' | 'fairy' | 'golem' | 'human' | 'human_magical' | 'kangaroo' | 'magical_toaster' | 'reptilian' | 'robot' | 'undead' | 'unicorn' | 'vampire' | 'zeta_reticulan_grey';

export type CharacterRarity = 'epic' | 'legendary' | 'mythic' | 'rare' | 'uncommon';

export type PowerTier = 'ability' | 'signature' | 'skill' | 'species';

export type SpellTier = 'archetype' | 'signature' | 'species' | 'universal';
