
import { GameEventBus, GameEvent } from './gameEventBus';
import { recordBondActivity } from './bondTrackingService';

/**
 * Initialize bond event subscriptions
 * This should be called on server startup
 */
export function initializeBondEventSubscriptions() {
    const eventBus = GameEventBus.get_instance();

    console.log('🔗 [BOND] Initializing bond event subscriptions...');

    // Subscribe to Battle Victory
    eventBus.subscribe('battle_victory', async (event: GameEvent) => {
        try {
            console.log(`🔗 [BOND] Processing battle victory for ${event.userchar_ids.length} characters`);

            // Record bond increase for ALL participants equally
            for (const char_id of event.userchar_ids) {
                const other_chars = event.userchar_ids.filter(id => id !== char_id);
                await recordBondActivity({
                    user_character_id: char_id,
                    activity_type: 'battle_victory_together',
                    context: {
                        event_id: event.id,
                        battle_description: event.description,
                        teammates: other_chars
                    },
                    source: 'battle_system'
                });
            }

        } catch (error) {
            console.error('❌ [BOND] Error processing battle victory event:', error);
        }
    });

    // Subscribe to Level Up (Major Milestone)
    eventBus.subscribe('level_up', async (event: GameEvent) => {
        try {
            // Level up events have one character
            for (const char_id of event.userchar_ids) {
                console.log(`🔗 [BOND] Processing level up for character ${char_id}`);
                await recordBondActivity({
                    user_character_id: char_id,
                    activity_type: 'performance_coaching',
                    context: {
                        event_id: event.id,
                        level: event.metadata?.new_level,
                        description: 'Character reached a new level'
                    },
                    source: 'progression_system'
                });
            }
        } catch (error) {
            console.error('❌ [BOND] Error processing level up event:', error);
        }
    });

    // Subscribe to Ability Learned (Skill Milestone)
    eventBus.subscribe('ability_learned', async (event: GameEvent) => {
        try {
            for (const char_id of event.userchar_ids) {
                console.log(`🔗 [BOND] Processing ability learned for character ${char_id}`);
                await recordBondActivity({
                    user_character_id: char_id,
                    activity_type: 'performance_coaching',
                    context: {
                        event_id: event.id,
                        ability: event.metadata?.ability_name,
                        description: 'Character learned a new ability'
                    },
                    source: 'progression_system'
                });
            }
        } catch (error) {
            console.error('❌ [BOND] Error processing ability learned event:', error);
        }
    });

    // Subscribe to Financial Events (if emitted by event bus)
    eventBus.subscribe('trust_gained', async (event: GameEvent) => {
        // This might be redundant if we handle it in the route, but good as a backup
        // or for events generated by the simulation engine
        if (event.source === 'financial_advisory') {
            // Handle financial trust events
        }
    });

    console.log('✅ [BOND] Subscriptions initialized');
}
